# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  services.fstrim.enable = true;

  services.xserver.videoDrivers = lib.mkDefault [ "modesetting" ];

  services.undervolt = {
    enable = true;
    coreOffset = -100;
    uncoreOffset = -100;
    analogioOffset = -100;
    gpuOffset = -100;
  };

  hardware.graphics = {
    enable = lib.mkDefault true;
    enable32Bit = lib.mkDefault true;
    extraPackages = with pkgs; [
      vpl-gpu-rt
      intel-media-driver
      intel-vaapi-driver
      libva-vdpau-driver
      libvdpau-va-gl
    ];
    extraPackages32 = with pkgs.driversi686Linux; [
      intel-media-driver
      intel-vaapi-driver
      libvdpau-va-gl
    ];
  };

  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "iHD";
  };

  powerManagement.cpuFreqGovernor = "performance";
  services.thermald.enable = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "psmouse.synaptics_intertouch=0" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9982bd44-cfaa-4959-8e30-3341f728c29a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3165c377-6b98-498c-bd86-20a8fc530e9d".device = "/dev/disk/by-uuid/3165c377-6b98-498c-bd86-20a8fc530e9d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4DA8-3F95";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  services.pipewire.enable = lib.mkForce false;
  hardware.pulseaudio.enable = true;
  hardware.pulseaudio.daemon.config = {
    default-sample-format = "float32ne";
    default-sample-rate = 48000;
    alternate-sample-rate = 44100;
    default-sample-channels = 2;
    default-channel-map = "front-left,front-right";
    default-fragments = 2;
    default-fragment-size-msec = 125;
    resample-method = "speex-float-5";
    enable-lfe-remixing = "no";
    high-priority = "yes";
    nice-level = -11;
    realtime-scheduling = "yes";
    realtime-priority = 9;
    rlimit-rtprio = 9;
    rlimit-rttime = -1;
    daemonize = "no";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
