# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  services.fstrim.enable = true;
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "ums_realtek"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "ip_tables"
    "i6table_nat"
    "wireguard"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ea03d496-2769-485d-b5cb-de0b58cb698c";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4F5E-11FB";
    fsType = "vfat";
  };

  swapDevices = [ ];

  services.btrfs.autoScrub = {
    enable = true;
    interval = "weekly";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-df7898ffaebc.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-e6c4f9058f19.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth00e4385.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth0814d46.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth329e18d.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth54f044d.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth71ad87e.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8a14ed4.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth906e2ca.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth95a2121.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth96c8b25.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth97cb8cc.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9f4b444.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb88cfbb.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethc1707ca.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethec441e8.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethed69a4e.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf0728b9.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable OpenGL
  hardware.opengl = {
    enable = true;
  };

}
